import type { InventoryItem, Category } from './types';

export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: '1',
    name: 'Quantum Laptops',
    sku: 'QL-2024-A1',
    description: 'High-performance laptop for professionals and creatives.',
    quantity: 42,
    minStock: 10,
    price: 1499.99,
    supplier: 'Quantum Computing Inc.',
    category: 'Electronics',
    tags: ['laptop', 'high-performance', 'new'],
    lastUpdated: '2024-07-20T10:00:00Z',
    salesData: [
      { month: 'Jan', sales: 25 }, { month: 'Feb', sales: 30 }, { month: 'Mar', sales: 45 },
      { month: 'Apr', sales: 40 }, { month: 'May', sales: 55 }, { month: 'Jun', sales: 60 },
    ],
  },
  {
    id: '2',
    name: 'Nebula-5 Wireless Mouse',
    sku: 'N5-WM-2024',
    description: 'Ergonomic wireless mouse with 8 programmable buttons.',
    quantity: 115,
    minStock: 25,
    price: 79.99,
    supplier: 'Stellar Peripherals',
    category: 'Accessories',
    tags: ['mouse', 'wireless', 'ergonomic'],
    lastUpdated: '2024-07-21T11:30:00Z',
     salesData: [
      { month: 'Jan', sales: 120 }, { month: 'Feb', sales: 130 }, { month: 'Mar', sales: 155 },
      { month: 'Apr', sales: 140 }, { month: 'May', sales: 165 }, { month: 'Jun', sales: 180 },
    ],
  },
  {
    id: '3',
    name: 'Aether Mechanical Keyboard',
    sku: 'AMK-RGB-01',
    description: 'RGB mechanical keyboard with customizable switches.',
    quantity: 8,
    minStock: 15,
    price: 189.50,
    supplier: 'Stellar Peripherals',
    category: 'Accessories',
    tags: ['keyboard', 'mechanical', 'rgb'],
    lastUpdated: '2024-07-22T09:00:00Z',
     salesData: [
      { month: 'Jan', sales: 40 }, { month: 'Feb', sales: 45 }, { month: 'Mar', sales: 60 },
      { month: 'Apr', sales: 55 }, { month: 'May', sales: 70 }, { month: 'Jun', sales: 75 },
    ],
  },
  {
    id: '4',
    name: 'Centauri 34" Ultrawide Monitor',
    sku: 'CM-UWQHD-34',
    description: '34-inch ultrawide QHD monitor with 144Hz refresh rate.',
    quantity: 23,
    minStock: 5,
    price: 799.00,
    supplier: 'Visionary Displays',
    category: 'Electronics',
    tags: ['monitor', 'ultrawide', 'gaming'],
    lastUpdated: '2024-07-19T14:00:00Z',
     salesData: [
      { month: 'Jan', sales: 15 }, { month: 'Feb', sales: 20 }, { month: 'Mar', sales: 22 },
      { month: 'Apr', sales: 28 }, { month: 'May', sales: 35 }, { month: 'Jun', sales: 32 },
    ],
  },
  {
    id: '5',
    name: 'Orion Power Bank 20000mAh',
    sku: 'OPB-20K-C',
    description: 'High-capacity power bank with USB-C PD.',
    quantity: 250,
    minStock: 50,
    price: 49.99,
    supplier: 'Volt-Tech',
    category: 'Accessories',
    tags: ['power bank', 'portable', 'usb-c'],
    lastUpdated: '2024-07-22T15:20:00Z',
     salesData: [
      { month: 'Jan', sales: 200 }, { month: 'Feb', sales: 220 }, { month: 'Mar', sales: 250 },
      { month: 'Apr', sales: 240 }, { month: 'May', sales: 280 }, { month: 'Jun', sales: 300 },
    ],
  },
  {
    id: '6',
    name: 'Galileo Smart Projector',
    sku: 'GSP-4K-2024',
    description: '4K smart projector with built-in streaming apps.',
    quantity: 18,
    minStock: 10,
    price: 650.00,
    supplier: 'Visionary Displays',
    category: 'Electronics',
    tags: ['projector', '4k', 'smart'],
    lastUpdated: '2024-07-18T18:00:00Z',
  },
];

export const CATEGORIES: Category[] = [
  { name: 'Electronics', itemCount: 3 },
  { name: 'Accessories', itemCount: 3 },
  { name: 'Components', itemCount: 0 },
  { name: 'Office Supplies', itemCount: 0 },
];
